project:
  type: website

website:
  title: "personal teaching scripts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - r-setup.qmd
      - rmarkdown.qmd
      - publishing-to-web.qmd
      - data-vis.qmd
      - r-practice.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

